### ISSUE TITLE
bug: seems like its showing an old month in the graph

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yBuyback#50]
![image](https://user-images.githubusercontent.com/38810205/211069818-f24c02f5-d7e7-4aad-9c3d-d11332a89d98.png)
Maybe a sort issue?

**Comment by karelianpie** [comment]
@DarkGhost7 are you still seeing this issue? Seems to be working as expected:

<img width="1230" alt="Screenshot 2023-01-09 at 5 45 47 pm" src="https://user-images.githubusercontent.com/78794805/211348706-10319a11-70a1-4ebb-a672-26171ee0e517.png">

**Comment by DarkGhost7** [comment]
Yes @karelianpie 
![image](https://user-images.githubusercontent.com/38810205/211358410-917804a1-8c1c-4582-95cb-adcbd248624a.png)

**Comment by karelianpie** [comment]
@DarkGhost7 can you please give me some steps to reproduce that and also what environment are you seeing that in? 

When I visit https://buyback.yearn.finance/ it's working as expected

<img width="1219" alt="Screenshot 2023-01-09 at 6 49 53 pm" src="https://user-images.githubusercontent.com/78794805/211362501-5c9fa5d9-703f-4301-9a93-4358b83f1985.png">

When I log the data I also get Jan 2023 as the last element:

<img width="671" alt="Screenshot 2023-01-09 at 6 53 56 pm" src="https://user-images.githubusercontent.com/78794805/211363357-455c56aa-be75-4d57-a92e-296be8ee1da1.png">

**Comment by karelianpie** [comment]
Also, your graph seems slightly different from mine. 

For example, you don't seem to have this checkbox on the top right of the graph:
<img width="127" alt="Screenshot 2023-01-09 at 7 00 39 pm" src="https://user-images.githubusercontent.com/78794805/211364708-115fe88d-df69-48ae-8a34-8e0cf7266b71.png">

Your Y axis is also different, where are you seeing that graph?

**Comment by DarkGhost7** [comment]
https://buyback.yearn.finance is where I see it

**Comment by karelianpie** [comment]
> https://buyback.yearn.finance is where I see it

Which browser are you using?
